### ISSUE TITLE
Simple fix for SR-HC501 PIR Sensor (No Soldering) 

### ISSUE THREAD

**Issue by thehaxxa** [CCHS-Melbourne/ESPlant#18]
As per this guide http://randomnerdtutorials.com/modifying-cheap-pir-motion-sensor-to-work-at-3-3v/

The SR-HC501 PIR sensor can in fact (unofficially) use 3.3V as its using a (5V - 3.3V) Voltage Regulator anyway, simply moving the VCC Source from the VCC IN to any header past the Voltage Regulator enables the Sensor to work. 

(Here is the position of the header that 3.3V IN can be attached to)
![pir-fix](https://cloud.githubusercontent.com/assets/2765052/12778632/d6610482-cab7-11e5-9fd2-5134e980fbe6.png)

Please note this is untested as I had no Jumper cables on me, but has worked in previous projects.

**Comment by projectgus** [comment]
Thanks, this is so simple! I was thinking we'd have to desolder the LDO and bridge across it to get here. Will test and update the documentation if it works OK (which it seems like it will).
