### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by RobynWillison** [CCHS-Melbourne/ESPlant#22]
On the page https://github.com/CCHS-Melbourne/ESPlant/wiki/Internal-Sensors the link to the BME280 is dead. It should be http://www.bosch-sensortec.com/en/bst/products/all_products/bme280

Robyn

**Comment by adricl** [comment]
Hello Robyn,
I have fixed the link but you can also fix the link by going to the edit button on the wiki. 
Thanks for the fix,

Adric
